### ISSUE TITLE
Custom svn path

### ISSUE THREAD

**Issue by Mousaka** [emolchanov/npm-svn#1]
Hi,
First off, nice npm-module!

Suggestion:
Would be nice to be able to add a custom path to a folder inside trunk in a svn repo.
E.g.
"svn-module": "svn://path/to/svn/repo/trunk/FrontEndFolder",

If I do that now it adds trunk at the end which will make the path invalid.

Cheers

**Comment by p2227** [comment]
@Mousaka I get the same problem now.Why did u close the PR ?

**Comment by Mousaka** [comment]
@p2227 Because @hmoffatt suggested a better solution

> Wouldn't it be better if it didn't force the format of the svn repo at all? Why shouldn't I be able to use:
> 
> svn+ssh://my-server.company.com/srv/svn/my_repo/branches/my_branch/path/to/my/module

so that would probably be a better way to go. But I've got no time to fix that atm. You can still use my fork though if you want to. (Also the repo owner seemed to ignore my PR for a very long time)

**Comment by p2227** [comment]
@emolchanov are you  planning to publish a new version to NPM ?

**Comment by emolchanov** [comment]
Yep, at the end of this week.

**Comment by emolchanov** [comment]
@p2227 @Mousaka version v0.2.0 released with your PR and update dependencies. 
Please, let's me know, if you find bugs.
