### ISSUE TITLE
Not able to use repositories with no "trunk" folder

### ISSUE THREAD

**Issue by vitche** [emolchanov/npm-svn#3]
The default behavior for the library is to substitute "trunk" as a tag if no tag was specified. That is not correct when the user wants just to use a random path without specifying any tags.

The following line can be corrected to an empty string to make the library more flexible:
https://github.com/emolchanov/npm-svn/blob/master/src/scanner.js#L68

**Comment by emolchanov** [comment]
yep, can you fix that?
